### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file (models.py, line 30)

### ISSUE THREAD

**Issue by HeathHollows** [itsmewulf/dsc.py#5]
**Describe the bug**
When trying to load the cog that `import dsc` is used in, the console logs that there is a `SyntaxError`.

**To Reproduce**
1. Add `import dsc` to the beginning of a cog.
2. Go to start the bot
3. See error

**Expected behavior**
The cog should load and run as normal.

**Screenshots**
<img src="https://hhollows.ga/-Zu-SjpzB"
     alt="Screenshot of The Console Error" />

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
I did try to do this outside of a Discord Bot and still got the same error.

**Comment by itsmewulf** [comment]
Fixed now 👍
